language: c

compiler:
  - gcc
  - clang

# start the autotools chain, because we won't track generated files in git
before_script: autoreconf -i

# Default is:
# script: "./configure && make && make test"

after_success:
  - ./hello
  - git clean -fd
