language: c

compiler:
  - gcc
#  - clang

# start the autotools chain, because we won't track generated files in git
before_script: autoreconf -i

# Default is:
#   script: "./configure && make && make test"
# but autotools generates:
script: "./configure && make && make check"

after_success:
  - ./hello

# after_failure:
#   - cat test-suite.log

after_script:
  - git clean -fdX
