language: c

compiler:
  - gcc
  - clang

# start the autotools chain, because we won't track generated files in git
before_script: autoreconf -i

# Default is "./configure && make && make test", but no tests yet
script: "./configure && make"

after_success:
  - src/hello
  - git clean -fd
